#! /usr/bin/python

import sys
import os

dirs = open(".current").read().split()

if len(sys.argv) > 1:
    f = open(".current", "w")
    f.write(" ".join(sys.argv[1:]))
    f.close()
else:
    f = open(".current", "w")
    f.close()