#! /usr/local/bin/python3

import sys
import os
import argparse
import argcomplete
from pyplateau.utils import get_available_dirs

def main(args):
    if args.help:
        print("This is a help message for 'fcd'.")
    else:
        dirs = open(".current").read().split()

        if len(args.tags) >= 1:
            f = open(".current", "w")
            f.write(" ".join(args.tags))
            f.close()
        else:
            f = open(".current", "w")
            f.close()

if __name__ == '__main__':
    available_dirs = get_available_dirs()
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-h", "--help", action='store_true')
    parser.add_argument("tags", type=str, nargs="*", default=[])
    #argcomplete.autocomplete(parser)
    args = parser.parse_args()
    main(args)