#! /usr/local/bin/python3

import sys
import os
import argparse
import argcomplete

from pyplateau.utils import get_available_dirs, get_current_dirs, get_files

def main(args):
    if args.help:
        print("This is a help message for 'fopen'")
    elif len(args.files) >= 1:
        selected_dirs = get_current_dirs()
        available_dirs = get_available_dirs()
        available_files = get_files(selected_dirs, available_dirs)

        if len(available_files) > 0:
            for f in available_files:
                if f.split("_")[-1] in args.files:
                    os.system("open .files/" + f)

if __name__ == '__main__':
    available_dirs = get_available_dirs()
    selected_dirs = get_current_dirs()
    available_files = get_files(selected_dirs, available_dirs)
    available_files = [f.split("_")[-1] for f in available_files]
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("files", type=str, nargs="*", choices=available_files + [[]])
    argcomplete.autocomplete(parser)
    parser.add_argument("-h", "--help", action='store_true')
    args = parser.parse_args()
    main(args)
