#! /usr/local/bin/python3

import sys
import os
import argparse
import argcomplete

from pyplateau.utils import (
    get_available_dirs,
    get_current_dirs,
    get_files,
    open_files,
)

def main(args):
    if args.help:
        print("This is a help message for 'fopen'")
    else:
        filenames = args.files
        open_files(filenames)

if __name__ == '__main__':
    available_dirs = get_available_dirs()
    selected_dirs = get_current_dirs()
    available_files = get_files(selected_dirs)
    available_files = [f.split("_")[-1] for f in available_files]
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("files", type=str, nargs="*", choices=available_files + [[]])
    argcomplete.autocomplete(parser)
    parser.add_argument("-h", "--help", action='store_true')
    args = parser.parse_args()
    main(args)
