#! /usr/bin/python

import sys
import os

def get_files(dirs, available_dirs):
    if len(dirs) == 0:
        print("Filesystem root")
        return []
    else:
        all_found = True
        for d in dirs:
            if d not in available_dirs:
                all_found = False
        if all_found:
            allfiles = {}
            for ad in dirs:
                afiles = open(".dirs/" + ad).read().split()
                for f in afiles:
                    allfiles[f] = allfiles.get(f, 0) + 1

            allfiles = [f for f in allfiles if allfiles[f] == len(dirs)]
            #allfiles = ["_".join(f.split("_")[1:]) for f in allfiles]
            return allfiles
        else:
            print("No files")
            return []

dirs = open(".current").read().split()
available_dirs = sorted(os.listdir(".dirs"))
files = get_files(dirs, available_dirs)

if len(files) > 0:
    for f in files:
        os.system("open .files/" + f)
    