#! /usr/bin/python

import sys
import os
import argparse
from pyplateau.utils import (
    get_available_dirs,
    get_current_dirs,
    get_files,
    tag_file
)

def main(args):
    if args.help:
        print("This is a help message for 'ftag'")
    else:
        tag_file(args.file, args.tags)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-h", "--help", action='store_true')
    parser.add_argument("-d", "--del", action='store_true')
    parser.add_argument("file", type=str)
    parser.add_argument("tags", type=str, nargs="*", default=[])
    args = parser.parse_args()
    main(args)
