#! /usr/bin/python

import sys
import os
import random
import string
import argparse
from pyplateau.utils import (
    get_available_dirs,
    get_current_dirs,
    get_files,
    touch_files
)

def main(args):
    if args.h:
        print("Help text for 'ftouch'")
    else:
        touch_files(args.files)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-h", "--help", action='store_true')
    parser.add_argument("files", type=str, nargs="*", default=[])
    args = parser.parse_args()

    if args.help:
        print("This is a help message for 'ftouch'")
    else:
        main(args)