#! /usr/bin/python

import sys
import os
import random
import string
letters = string.ascii_lowercase

filename = ''.join(random.choice(letters) for i in range(16))

dirs = open(".current").read().split()
available_dirs = sorted(os.listdir(".dirs"))

print("Current tags:", dirs)

if len(sys.argv) > 1:
    print(sys.argv)
    if len(dirs) == 0:
        print("No tags available; can't create file!")
        print("Available tags:")
        if len(available_dirs) < 7:
            print("\n".join(available_dirs))
        else:
            print("\n".join(available_dirs[:5]))
            print("...")
            print("\n".join(available_dirs[-1:]))
    else:
        humanname = sys.argv[1]
        filename = filename + "_" + humanname
        print("Create file:", filename)

        for d in dirs:
            dpath = ".dirs/" + d
            d_content = open(dpath).read().split()
            d_content = d_content + [filename]

            f = open(dpath, "w")
            f.write(" ".join(d_content))
            f.close()

        filename = ".files/" + filename
        f = open(filename, "w")
        f.close()

