#! /usr/bin/python

import sys
import os
import random
import string
import argparse
from pyplateau.utils import get_available_dirs, get_current_dirs, get_files

def main(args):
    letters = string.ascii_lowercase

    available_dirs = get_available_dirs()
    selected_dirs = get_current_dirs()
    current_files = get_files(selected_dirs, available_dirs)
    humanreadable_current_files = [f.split("_")[-1] for f in current_files]

    if len(args.files) >= 1:
        if len(selected_dirs) == 0:
            print("No tags available; can't create file!")
            print("Available tags:")
            if len(available_dirs) < 7:
                print("\n".join(available_dirs))
            else:
                print("\n".join(available_dirs[:5]))
                print("...")
                print("\n".join(available_dirs[-1:]))
        else:
            for humanname in args.files:
                if humanname not in humanreadable_current_files:
                    filename = ''.join(random.choice(letters) for i in range(16))
                    filename = filename + "_" + humanname
                    print("Create file: " + humanname)

                    for d in selected_dirs:
                        dpath = ".dirs/" + d
                        d_content = open(dpath).read().split()
                        d_content = d_content + [filename]

                        f = open(dpath, "w")
                        f.write(" ".join(d_content))
                        f.close()

                    filename = ".files/" + filename
                    f = open(filename, "w")
                    f.close()
                else:
                    print(humanname + " already exists for these tags!")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("-h", "--help", action='store_true')
    parser.add_argument("files", type=str, nargs="*", default=[])
    args = parser.parse_args()

    if args.help:
        print("This is a help message for 'ftouch'")
    else:
        main(args)